Add info about some bulk expanding do not allow all.
queicherius/gw2api-client pull request #84
Opened 2024-10-26 15:56 UTC by Ecmelt

2024-10-27 05:19 UTC, queicherius requested changes
I think this comment should go somewhere else (but I'm not entirely sure where), since that particular documentation is more for the end-user of the library and not authors.

2024-10-27 12:14 UTC, Ecmelt commented
Unsure too, because i thought of readme which actually has "this.supportsBulkAll = false" in the items example but that is not really a good explanation of what it does and so very easy to miss.

2024-10-27 16:23 UTC, queicherius commented
Yeah maybe update https://github.com/queicherius/gw2api-client/blob/master/README.md#extending to add comments above each of the `this.configValue = foo` lines explaining what they do?

2024-10-30 18:29 UTC, queicherius approved these changes

2024-10-30 18:29 UTC, merged